changes: - updated the overlay files although need to rewrite the apache files - updated the dockerfile so now fully building and seems to run just apache not working

diff --git a/alpine/xlx/Dockerfile b/alpine/xlx/Dockerfile
--- a/alpine/xlx/Dockerfile
+++ b/alpine/xlx/Dockerfile
@@ -15,41 +15,47 @@ ARG YSF_DEFAULT_NODE_RX_FREQ=438000000 YSF_DEFAULT_NODE_TX_FREQ=438000000
 ARG S6_OVERLAY_VERSION=3.2.0.2 S6_OVERLAY_INST=/src/S6
 ARG S6_OVERLAY_ADDRESS=https://github.com/just-containers/s6-overlay/releases/download/v
 
-##libapache2-mod-php \
-
+## mounting a cache volume - then apk updates and adds
 RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
     apk update && \
     apk add --virtual build-dependencies && \
     apk add --update --no-cache \
         alpine-sdk build-base linux-headers \
-        bash xz && \
+        bash curl xz && \
     apk add --update --no-cache \
         --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ \
         apache2 php81 php81-mbstring php81-apache2
 
+## making dirs for installs
 RUN mkdir -p \
     ${S6_OVERLAY_INST} \
     ${XLXD_DIR} \
     ${XLXD_INST_DIR} \
     ${XLXD_WEB_DIR}
 
+## installing the s6_overlay noarch
+RUN wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz" \
+        -O "${S6_OVERLAY_INST}/s6-overlay-noarch.tar.xz" && \
+    tar -C / -xJf "${S6_OVERLAY_INST}/s6-overlay-noarch.tar.xz"
+
+## installing the s6_overlay arch either arm || amd
 RUN if [ "${TARGETARCH}" = "arm64" ]; then \
-        cd "${S6_OVERLAY_INST}" && \
-        wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-aarch64.tar.xz" && \
-        tar -xJf "${S6_OVERLAY_INST}/s6-overlay-aarch64.tar.xz" && \
-        mv * / ; \
+        wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-aarch64.tar.xz" \
+            -O "${S6_OVERLAY_INST}/s6-overlay-aarch64.tar.xz" && \
+        tar -C / -xJf "${S6_OVERLAY_INST}/s6-overlay-aarch64.tar.xz" ; \
     elif [ "${TARGETARCH}" = "amd64" ]; then \
-        cd "${S6_OVERLAY_INST}" && \
-        wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz" && \
-        tar -xJf "${S6_OVERLAY_INST}/s6-overlay-x86_64.tar.xz" && \
-        mv * / ; \
+        wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz" \
+            -O "${S6_OVERLAY_INST}/s6-overlay-x86_64.tar.xz" && \
+        tar -C / -xJf "${S6_OVERLAY_INST}/s6-overlay-x86_64.tar.xz" ; \
     else \
         echo "DANGER WILL ROBINSON. UNKNOWN TARGETARCH" && \
-        exit 1; \
+        exit 1 ; \
     fi
 
+## pulling repo xlxd
 ADD --keep-git-dir=true https://github.com/LX3JL/xlxd.git#master ${XLXD_INST_DIR}
 
+## sed edits for xlxd config
 RUN sed -i "s/\#define\ RUN_AS_DAEMON/\/\/\#define\ RUN_AS_DAEMON/g" ${XLXD_INST_DIR}/src/main.h && \
     sed -i "1!b;s/\(NB_OF_MODULES[[:blank:]]*\)[[:digit:]]*/\1${MODULES}/g" ${XLXD_INST_DIR}/src/main.h && \
     sed -i "s/\(YSF_AUTOLINK_ENABLE[[:blank:]]*\)[[:digit:]]/\1${YSF_AUTOLINK_ENABLE}/g" ${XLXD_INST_DIR}/src/main.h && \
@@ -60,21 +66,26 @@ RUN sed -i "s/\#define\ RUN_AS_DAEMON/\/\/\#define\ RUN_AS_DAEMON/g" ${XLXD_INST
     cp ${XLXD_INST_DIR}/src/main.h ${XLXD_DIR}/main.h.customized && \
     cp ${XLXD_INST_DIR}/src/cysfprotocol.cpp ${XLXD_DIR}/cysfprotocol.cpp.customized
 
+## making xlxd
 RUN cd ${XLXD_INST_DIR}/src && \
     make clean && \
     make && \
     make install
 
+## copying the dashboard
 RUN cp -ivR ${XLXD_INST_DIR}/dashboard/* ${XLXD_WEB_DIR}/
 
+## copying the s6 overlay from the repo. Will change this in the future to generate from Dockerfile
 COPY s6_overlay/ /
 
+## cleanup
 RUN rm -rf /var/cache/apk/* && \
     rm -rf /var/lib/apt/lists/* && \
     rm -rf /tmp/* && \
     rm -rf /var/tmp/* && \
     rm -rf /src
 
+## exposing needed ports
 EXPOSE 80/tcp
 EXPOSE 8080/tcp
 EXPOSE 8880/udp
