changes: - moved alpine/{xlx,ysf} to ../
delete:
- removed alpine folder

diff --git a/XLXd/Dockerfile b/XLXd/Dockerfile
--- a/XLXd/Dockerfile
+++ b/XLXd/Dockerfile
@@ -1,7 +1,6 @@
+## xlx
 # syntax=docker/dockerfile:1-labs
-FROM --platform=$BUILDPLATFORM ubuntu:latest AS base
-
-ENTRYPOINT [ "/init" ]
+FROM --platform=$BUILDPLATFORM alpine:latest
 
 ENV TERM="xterm" LANG="C.UTF-8" LC_ALL="C.UTF-8"
 ENV CALLHOME CALLSIGN COMMENT COUNTRY DESCRIPTION EMAIL PORT TZ URL XLXNUM
@@ -14,71 +13,157 @@ ARG YSF_DEFAULT_NODE_RX_FREQ=438000000 YSF_DEFAULT_NODE_TX_FREQ=438000000
 ARG S6_OVERLAY_VERSION=3.2.0.2 S6_OVERLAY_INST=/src/S6
 ARG S6_OVERLAY_ADDRESS=https://github.com/just-containers/s6-overlay/releases/download/v
 
-RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
-    apt update && \
-    apt upgrade -y && \
-    apt install -y \
-        apache2 \
-        build-essential \
-        curl \
-        libapache2-mod-php \
-        php \
-        php-mbstring \
-        wget
+## mounting a cache volume - then apk updates and adds
+RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
+    apk update \
+    && apk add --virtual build-dependencies \
+    && apk add --update --no-cache \
+        alpine-sdk build-base linux-headers \
+        bash curl xz \
+        apache2 apache2-utils \
+        php84 php84-apache2 php84-common php84-mbstring php84-session
 
+## making dirs for installs
 RUN mkdir -p \
     ${S6_OVERLAY_INST} \
     ${XLXD_DIR} \
     ${XLXD_INST_DIR} \
-    ${XLXD_WEB_DIR} && \
-    chown -R www-data:www-data ${XLXD_DIR}/
+    ${XLXD_WEB_DIR}
 
-RUN wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz" \
-        -O "${S6_OVERLAY_INST}/s6-overlay-noarch.tar.xz" && \
-    tar -C / -Jxpf "${S6_OVERLAY_INST}/s6-overlay-noarch.tar.xz"
+##########################
+###### xlxd install ######
+##########################
 
-RUN if [ "${TARGETARCH}" = "arm64" ]; then \
-        wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-aarch64.tar.xz" \
-            -O "${S6_OVERLAY_INST}/s6-overlay-aarch64.tar.xz" && \
-        tar -C / -Jxpf "${S6_OVERLAY_INST}/s6-overlay-aarch64.tar.xz"; \
-    elif [ "${TARGETARCH}" = "amd64" ]; then \
-        wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz" \
-            -O "${S6_OVERLAY_INST}/s6-overlay-x86_64.tar.xz" && \
-        tar -C / -Jxpf "${S6_OVERLAY_INST}/s6-overlay-x86_64.tar.xz"; \
-    else \
-        echo "DANGER WILL ROBINSON. UNKNOWN TARGETARCH" && \
-        exit 1; \
-    fi
-
+## pulling repo xlxd
 ADD --keep-git-dir=true https://github.com/LX3JL/xlxd.git#master ${XLXD_INST_DIR}
 
-RUN sed -i "s/\#define\ RUN_AS_DAEMON/\/\/\#define\ RUN_AS_DAEMON/g" ${XLXD_INST_DIR}/src/main.h && \
-    sed -i "1!b;s/\(NB_OF_MODULES[[:blank:]]*\)[[:digit:]]*/\1${MODULES}/g" ${XLXD_INST_DIR}/src/main.h && \
-    sed -i "s/\(YSF_AUTOLINK_ENABLE[[:blank:]]*\)[[:digit:]]/\1${YSF_AUTOLINK_ENABLE}/g" ${XLXD_INST_DIR}/src/main.h && \
-    sed -i "s/\(YSF_AUTOLINK_MODULE[[:blank:]]*\)'[[:alpha:]]'/\1\'${YSF_AUTOLINK_MODULE}\'/g" ${XLXD_INST_DIR}/src/main.h && \
-    sed -i "s/\(YSF_PORT[[:blank:]]*\)[[:digit:]]/\1${YSF_PORT}/g" ${XLXD_INST_DIR}/src/main.h && \
-    sed -i "s/\(YSF_DEFAULT_NODE_RX_FREQ[[:blank:]]*\)[[:digit:]]*/\1${YSF_DEFAULT_NODE_RX_FREQ}/g" ${XLXD_INST_DIR}/src/main.h && \
-    sed -i "s/\(YSF_DEFAULT_NODE_TX_FREQ[[:blank:]]*\)[[:digit:]]*/\1${YSF_DEFAULT_NODE_TX_FREQ}/g" ${XLXD_INST_DIR}/src/main.h && \
-    cp ${XLXD_INST_DIR}/src/main.h ${XLXD_DIR}/main.h.customized && \
-    cp ${XLXD_INST_DIR}/src/cysfprotocol.cpp ${XLXD_DIR}/cysfprotocol.cpp.customized
+## sed edits for xlxd config
+RUN sed -i "s/\#define\ RUN_AS_DAEMON/\/\/\#define\ RUN_AS_DAEMON/g" ${XLXD_INST_DIR}/src/main.h \
+    && sed -i "1!b;s/\(NB_OF_MODULES[[:blank:]]*\)[[:digit:]]*/\1${MODULES}/g" ${XLXD_INST_DIR}/src/main.h \
+    && sed -i "s/\(YSF_AUTOLINK_ENABLE[[:blank:]]*\)[[:digit:]]/\1${YSF_AUTOLINK_ENABLE}/g" ${XLXD_INST_DIR}/src/main.h \
+    && sed -i "s/\(YSF_AUTOLINK_MODULE[[:blank:]]*\)'[[:alpha:]]'/\1\'${YSF_AUTOLINK_MODULE}\'/g" ${XLXD_INST_DIR}/src/main.h \
+    && sed -i "s/\(YSF_PORT[[:blank:]]*\)[[:digit:]]/\1${YSF_PORT}/g" ${XLXD_INST_DIR}/src/main.h \
+    && sed -i "s/\(YSF_DEFAULT_NODE_RX_FREQ[[:blank:]]*\)[[:digit:]]*/\1${YSF_DEFAULT_NODE_RX_FREQ}/g" ${XLXD_INST_DIR}/src/main.h \
+    && sed -i "s/\(YSF_DEFAULT_NODE_TX_FREQ[[:blank:]]*\)[[:digit:]]*/\1${YSF_DEFAULT_NODE_TX_FREQ}/g" ${XLXD_INST_DIR}/src/main.h \
+    && cp ${XLXD_INST_DIR}/src/main.h ${XLXD_DIR}/main.h.customized \
+    && cp ${XLXD_INST_DIR}/src/cysfprotocol.cpp ${XLXD_DIR}/cysfprotocol.cpp.customized
 
-RUN cd ${XLXD_INST_DIR}/src && \
-    make clean && \
-    make && \
-    make install
+## making xlxd
+RUN cd ${XLXD_INST_DIR}/src \
+    && make clean \
+    && make \
+    && make install
 
-RUN cp -ivR ${XLXD_INST_DIR}/dashboard/* ${XLXD_WEB_DIR}/ && \
-    chown -R www-data:www-data ${XLXD_WEB_DIR}/
+## copying the dashboard
+RUN cp -ivR ${XLXD_INST_DIR}/dashboard/* ${XLXD_WEB_DIR}/
 
-COPY s6_overlay/ /
+#################################
+###### s6 overlay install  ######
+#################################
 
-RUN apt -y purge build-essential && \
-    apt -y autoremove && \
-    apt -y clean && \
-    rm -rf /var/lib/apt/lists/* && \
-    rm -rf /tmp/* && \
-    rm -rf /var/tmp/* && \
-    rm -rf /src
+## installing the s6_overlay noarch
+RUN wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz" \
+        -O "${S6_OVERLAY_INST}/s6-overlay-noarch.tar.xz" \
+    && tar -C / -xJf "${S6_OVERLAY_INST}/s6-overlay-noarch.tar.xz"
+
+## installing the s6_overlay arch either arm || amd
+RUN if [ "${TARGETARCH}" = "arm64" ]; then \
+        wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-aarch64.tar.xz" \
+            -O "${S6_OVERLAY_INST}/s6-overlay-aarch64.tar.xz" \
+        && tar -C / -xJf "${S6_OVERLAY_INST}/s6-overlay-aarch64.tar.xz" ; \
+    elif [ "${TARGETARCH}" = "amd64" ]; then \
+        wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz" \
+            -O "${S6_OVERLAY_INST}/s6-overlay-x86_64.tar.xz" \
+        && tar -C / -xJf "${S6_OVERLAY_INST}/s6-overlay-x86_64.tar.xz" ; \
+    else \
+        echo "DANGER WILL ROBINSON. UNKNOWN TARGETARCH" \
+        && exit 1 ; \
+    fi
+
+#####################################
+###### s6 overlay config begin ######
+#####################################
+
+#### xlx ####
+
+## Define xlxd as a long running s6 service
+COPY <<EOF /etc/s6-overlay/s6-rc.d/xlxd/type
+longrun
+EOF
+
+## Define entrypoint for xlxd && start in foreground
+COPY --chmod=700 scripts/xlxd_run.sh /etc/s6-overlay/s6-rc.d/xlxd/run
+
+## register xlxd as a service for s6
+RUN touch /etc/s6-overlay/s6-rc.d/user/contents.d/xlxd
+
+## register dependencies 
+RUN mkdir /etc/s6-overlay/s6-rc.d/xlxd/dependencies.d/ \
+    && touch /etc/s6-overlay/s6-rc.d/xlxd/dependencies.d/customize \
+    && touch /etc/s6-overlay/s6-rc.d/xlxd/dependencies.d/base
+
+
+#### httpd ####
+
+## define httpd as a long running s6 service
+COPY <<EOF /etc/s6-overlay/s6-rc.d/httpd/type
+longrun
+EOF
+
+## define entrypoint for httpd && start in foreground
+COPY --chmod=700 <<EOF /etc/s6-overlay/s6-rc.d/httpd/run
+#!/command/with-contenv sh
+exec /usr/sbin/httpd -D FOREGROUND
+EOF
+
+## register httpd as a service for s6
+RUN touch /etc/s6-overlay/s6-rc.d/user/contents.d/httpd
+
+## register dependencies 
+RUN mkdir /etc/s6-overlay/s6-rc.d/httpd/dependencies.d/ \
+    && touch /etc/s6-overlay/s6-rc.d/httpd/dependencies.d/xlxd \
+    && touch /etc/s6-overlay/s6-rc.d/httpd/dependencies.d/customize \
+    && touch /etc/s6-overlay/s6-rc.d/httpd/dependencies.d/base
+
+
+#### httpd customization script ####
+
+## define httpd customization as a oneshot service
+COPY <<EOF /etc/s6-overlay/s6-rc.d/customize/type
+oneshot
+EOF
+
+## run httpd customize as oneshot run on up
+COPY --chmod=700 <<EOF /etc/s6-overlay/s6-rc.d/customize/up
+/etc/s6-overlay/scripts/customize.sh
+EOF
+
+## register httpd customization as a service for s6
+RUN touch /etc/s6-overlay/s6-rc.d/user/contents.d/customize
+
+## copying the httpd customization script to /etc/s6-overlay/scripts/customize.sh
+COPY --chmod=700 scripts/customize.sh /etc/s6-overlay/scripts/
+
+## register dependencies 
+RUN mkdir /etc/s6-overlay/s6-rc.d/customize/dependencies.d/ \
+    && touch /etc/s6-overlay/s6-rc.d/customize/dependencies.d/base
+
+###################################
+###### s6 overlay config end ######
+###################################
+
+#####################
+###### cleanup ######
+#####################
+
+RUN rm -rf /var/cache/apk/* \
+    && rm -rf /tmp/* \
+    && rm -rf /var/tmp/* \
+    && rm -rf /src
+
+############################
+###### exposing ports ######
+############################
 
 EXPOSE 80/tcp
 EXPOSE 8080/tcp
@@ -93,3 +178,9 @@ EXPOSE 30051/udp
 EXPOSE 40000/udp
 EXPOSE 42000-42005/udp
 EXPOSE 62030/udp
+
+########################
+###### entrypoint ######
+########################
+
+ENTRYPOINT ["/init"]
diff --git a/YSFReflector/Dockerfile b/YSFReflector/Dockerfile
--- a/YSFReflector/Dockerfile
+++ b/YSFReflector/Dockerfile
@@ -1,7 +1,6 @@
+## ysf
 # syntax=docker/dockerfile:1-labs
-FROM --platform=$BUILDPLATFORM ubuntu:latest AS base
-
-ENTRYPOINT ["/init"]
+FROM --platform=$BUILDPLATFORM alpine:latest
 
 ENV TERM="xterm" LANG="C.UTF-8" LC_ALL="C.UTF-8"
 ENV DESCRIPTION="" ID="" NAME="" PORT="42000" URL="" WEB_PORT="80"
@@ -11,71 +10,164 @@ ARG YSF_DASH_INST_DIR=/src/YSFDashboard
 ARG S6_OVERLAY_VERSION=3.2.0.2 S6_OVERLAY_INST=/src/S6
 ARG S6_OVERLAY_ADDRESS=https://github.com/just-containers/s6-overlay/releases/download/v
 
-RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
-    apt update && \
-    apt upgrade -y && \
-    apt install -y \
-        apache2 \
-        build-essential \
-        libapache2-mod-php \
-        php \
-        php-mbstring \
-        procps \
-        wget
+## mounting a cache volume - then apk updates and adds
+RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
+    apk update \
+    && apk add --virtual build-dependencies \
+    && apk add --update --no-cache \
+        alpine-sdk build-base linux-headers \
+        bash curl procps-ng xz  \
+        apache2 apache2-utils \
+        php84 php84-apache2 php84-common php84-mbstring php84-session
 
+## making dirs for installs
 RUN mkdir -p \
     ${YSF_DIR} \
     ${YSF_INST_DIR} \
     ${YSF_DASH_INST_DIR} \
     ${S6_OVERLAY_INST}
 
-RUN wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz" \
-        -O "${S6_OVERLAY_INST}/s6-overlay-noarch.tar.xz" && \
-    tar -C / -Jxpf "${S6_OVERLAY_INST}/s6-overlay-noarch.tar.xz"
+##################################
+###### YSFReflector Install ######
+##################################
 
-RUN if [ "${TARGETARCH}" = "arm64" ]; then \
-        wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-aarch64.tar.xz" \
-            -O "${S6_OVERLAY_INST}/s6-overlay-aarch64.tar.xz" && \
-        tar -C / -Jxpf "${S6_OVERLAY_INST}/s6-overlay-aarch64.tar.xz"; \
-    elif [ "${TARGETARCH}" = "amd64" ]; then \
-        wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz" \
-            -O "${S6_OVERLAY_INST}/s6-overlay-x86_64.tar.xz" && \
-        tar -C / -Jxpf "${S6_OVERLAY_INST}/s6-overlay-x86_64.tar.xz"; \
-    else \
-        echo "DANGER WILL ROBINSON. UNKNOWN TARGETARCH" && \
-        exit 1; \
-    fi
+#### reflector ####
 
 ADD --keep-git-dir=true https://github.com/nostar/DVReflectors.git#main ${YSF_INST_DIR}
 
-RUN cd ${YSF_INST_DIR}${YSF_DIR} && \
-    make clean && \
-    make && \
-    make all && \
-    cp ${YSF_INST_DIR}/YSFReflector/YSFReflector.ini ${YSF_DIR}/YSFReflector.ini && \
-    cp ${YSF_INST_DIR}/YSFReflector/YSFReflector ${YSF_DIR}/YSFReflector
+RUN cd ${YSF_INST_DIR}${YSF_DIR} \
+    && make clean \
+    && make \
+    && make all \
+    && cp ${YSF_INST_DIR}/YSFReflector/YSFReflector.ini ${YSF_DIR}/YSFReflector.ini \
+    && cp ${YSF_INST_DIR}/YSFReflector/YSFReflector ${YSF_DIR}/YSFReflector
+
+#### Dashboard ####
 
 ADD --keep-git-dir=true https://github.com/dg9vh/YSFReflector-Dashboard.git#master ${YSF_DASH_INST_DIR}
 
-RUN cp ${YSF_DASH_INST_DIR}/favicon.ico /var/www/html/ && \
-    cp ${YSF_DASH_INST_DIR}/index.php /var/www/html/ && \
-    cp ${YSF_DASH_INST_DIR}/txinfo.php /var/www/html/ && \
-    cp ${YSF_DASH_INST_DIR}/version.php /var/www/html/ && \
-    cp -r ${YSF_DASH_INST_DIR}/include/ /var/www/html/ && \
-    chown -R www-data:www-data /var/www/html && \
-    chmod -R 775 /var/www/html && \
-    rm -f /var/www/html/index.html
+RUN mkdir /var/www/html \
+    && cp ${YSF_DASH_INST_DIR}/favicon.ico /var/www/html/ \
+    && cp ${YSF_DASH_INST_DIR}/index.php /var/www/html/ \
+    && cp ${YSF_DASH_INST_DIR}/txinfo.php /var/www/html/ \
+    && cp ${YSF_DASH_INST_DIR}/version.php /var/www/html/ \
+    && cp -r ${YSF_DASH_INST_DIR}/include/ /var/www/html/ \
+    && rm -f /var/www/html/index.html
 
-COPY s6_overlay/ /
+#################################
+###### s6 overlay install  ######
+#################################
 
-RUN apt -y purge build-essential \
-        wget && \
-    apt -y autoremove && \
-    apt -y clean && \
-    rm -rf /var/lib/apt/lists/* && \
+## installing the s6_overlay noarch
+RUN wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz" \
+        -O "${S6_OVERLAY_INST}/s6-overlay-noarch.tar.xz" \
+    && tar -C / -xJf "${S6_OVERLAY_INST}/s6-overlay-noarch.tar.xz"
+
+## installing the s6_overlay arch either arm || amd
+RUN if [ "${TARGETARCH}" = "arm64" ]; then \
+        wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-aarch64.tar.xz" \
+            -O "${S6_OVERLAY_INST}/s6-overlay-aarch64.tar.xz" \
+        && tar -C / -xJf "${S6_OVERLAY_INST}/s6-overlay-aarch64.tar.xz" ; \
+    elif [ "${TARGETARCH}" = "amd64" ]; then \
+        wget "${S6_OVERLAY_ADDRESS}${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz" \
+            -O "${S6_OVERLAY_INST}/s6-overlay-x86_64.tar.xz" \
+        && tar -C / -xJf "${S6_OVERLAY_INST}/s6-overlay-x86_64.tar.xz" ; \
+    else \
+        echo "DANGER WILL ROBINSON. UNKNOWN TARGETARCH" \
+        && exit 1 ; \
+    fi
+
+#####################################
+###### s6 overlay config begin ######
+#####################################
+
+
+#### httpd ####
+
+## define httpd as a longrun s6 service
+COPY <<EOF /etc/s6-overlay/s6-rc.d/httpd/type
+longrun
+EOF
+
+## define entrypoint for httpd && start in foreground
+COPY --chmod=700 <<EOF /etc/s6-overlay/s6-rc.d/httpd/run
+#!/command/with-contenv sh
+exec /usr/sbin/httpd -D FOREGROUND
+EOF
+
+## register httpd as a service for s6
+RUN touch /etc/s6-overlay/s6-rc.d/user/contents.d/httpd
+
+## register dependencies
+RUN mkdir /etc/s6-overlay/s6-rc.d/httpd/dependencies.d/ \
+    && touch /etc/s6-overlay/s6-rc.d/httpd/dependencies.d/YSFReflector \
+    && touch /etc/s6-overlay/s6-rc.d/httpd/dependencies.d/customize \
+    && touch /etc/s6-overlay/s6-rc.d/httpd/dependencies.d/base
+
+
+#### httpd customization script ####
+
+## define httpd customization as a oneshot service
+COPY <<EOF /etc/s6-overlay/s6-rc.d/customize/type
+oneshot
+EOF
+
+## run httpd customize as oneshot run on up
+COPY --chmod=700 <<EOF /etc/s6-overlay/s6-rc.d/customize/up
+/etc/s6-overlay/scripts/customize.sh
+EOF
+
+## register httpd customization as a service for s6
+RUN touch /etc/s6-overlay/s6-rc.d/user/contents.d/customize
+
+## copying the httpd customization script to /etc/s6-overlay/scripts/customize.sh
+COPY --chmod=700 scripts/customize.sh /etc/s6-overlay/scripts/
+
+## register dependencies
+RUN mkdir /etc/s6-overlay/s6-rc.d/customize/dependencies.d/ \
+    && touch /etc/s6-overlay/s6-rc.d/customize/dependencies.d/base
+
+
+#### YSFReflector ####
+
+## define YSFReflector as a longrun s6 service
+COPY <<EOF /etc/s6-overlay/s6-rc.d/YSFReflector/type
+longrun
+EOF
+
+## define entrypoint for YSFReflector && start in foreground
+COPY --chmod=700 scripts/YSFReflector_run.sh /etc/s6-overlay/s6-rc.d/YSFReflector/run
+
+## register YSFReflector as a service for s6
+RUN touch /etc/s6-overlay/s6-rc.d/user/contents.d/YSFReflector
+
+## register dependencies
+RUN mkdir /etc/s6-overlay/s6-rc.d/YSFReflector/dependencies.d/ \
+    && touch /etc/s6-overlay/s6-rc.d/httpd/dependencies.d/base \
+    && touch /etc/s6-overlay/s6-rc.d/httpd/dependencies.d/customize
+
+###################################
+###### s6 overlay config end ######
+###################################
+
+#####################
+###### cleanup ######
+#####################
+
+RUN rm -rf /var/cache/apk/* && \
     rm -rf /tmp/* && \
     rm -rf /var/tmp/* && \
     rm -rf /src
 
+############################
+###### exposing ports ######
+############################
+
 EXPOSE 80/tcp
 EXPOSE 42000/udp
+
+########################
+###### entrypoint ######
+########################
+
+ENTRYPOINT ["/init"]
